In [49]:
print("Hello I'm excited to learn pytorch")

Hello I'm excited to learn pytorch


## 00. PyTorch Fundamentals

In [50]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to tensors

In [51]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [52]:
scalar.ndim

0

In [53]:
scalar.ndimension

<function Tensor.ndimension>

In [54]:
scalar.item()

7

In [55]:
# vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [56]:
vector.ndim

1

In [57]:
vector.shape

torch.Size([2])

In [58]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [59]:
MATRIX.ndim

2

In [60]:
MATRIX.shape

torch.Size([2, 2])

In [61]:
MATRIX[0][0]

tensor(7)

In [62]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR.ndim

3

In [63]:
TENSOR.shape

torch.Size([1, 3, 3])

In [64]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

In [65]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2535, 0.1701, 0.0907, 0.1213],
        [0.5299, 0.2728, 0.9474, 0.8683],
        [0.1583, 0.8190, 0.6141, 0.7198]])

In [66]:
random_tensor.ndim

2

In [67]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3))

In [68]:
random_image_size_tensor

tensor([[[0.3605, 0.3483, 0.6693],
         [0.2788, 0.0159, 0.4593],
         [0.2258, 0.3099, 0.1837],
         ...,
         [0.0577, 0.6418, 0.0208],
         [0.5682, 0.8008, 0.6876],
         [0.0569, 0.8242, 0.7559]],

        [[0.9985, 0.6347, 0.9428],
         [0.0641, 0.4894, 0.3659],
         [0.0503, 0.0927, 0.3836],
         ...,
         [0.5948, 0.5576, 0.4918],
         [0.4184, 0.1794, 0.3841],
         [0.1153, 0.4721, 0.2275]],

        [[0.7707, 0.2142, 0.4836],
         [0.3747, 0.5347, 0.1700],
         [0.8241, 0.4949, 0.4256],
         ...,
         [0.6215, 0.6699, 0.3800],
         [0.6083, 0.8059, 0.9028],
         [0.8507, 0.0610, 0.6967]],

        ...,

        [[0.6686, 0.3992, 0.9517],
         [0.9203, 0.9072, 0.8575],
         [0.5377, 0.2218, 0.3021],
         ...,
         [0.0842, 0.5334, 0.6488],
         [0.0850, 0.4552, 0.2542],
         [0.7695, 0.1117, 0.9000]],

        [[0.6458, 0.4689, 0.6026],
         [0.9511, 0.0262, 0.1557],
         [0.

In [69]:
random_image_size_tensor.ndimension()

3

## Zeros and Ones

In [70]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
ones.dtype

torch.float32

In [73]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [74]:
# use torch.range()

torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [76]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [77]:
torch.ones_like(one_to_ten)

tensor([1, 1, 1, 1, 1])

## Tensor DataTypes

In [78]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, # 'cpu'/'cuda'# What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [79]:
float_32_tensor.dtype

torch.float32

In [80]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [81]:
t = float_16_tensor*float_32_tensor
t.dtype

torch.float32

In [82]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
x=int_32_tensor*float_32_tensor
x.dtype

torch.float32

### Getting information from tensors

In [83]:
some_tensor = torch.rand(size=(4,3))
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.6426, 0.5694, 0.8623],
        [0.7314, 0.6492, 0.6056],
        [0.2550, 0.7385, 0.9783],
        [0.6899, 0.2552, 0.9321]])
Shape of tensor: torch.Size([4, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors

In [84]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [85]:
# Multiply it by 10
tensor*10

tensor([10, 20, 30])

In [86]:
tensor

tensor([1, 2, 3])

In [87]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [88]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [89]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [90]:
tensor

tensor([1, 2, 3])

In [91]:
print(tensor, "*", tensor)
print("Equals:", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


## Matrix Multiplication

In [92]:
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(3,2)
torch.matmul(tensor1, tensor2)

tensor([[0.6349, 0.5953],
        [0.5459, 0.3805]])

In [93]:
tensor1 @ tensor2

tensor([[0.6349, 0.5953],
        [0.5459, 0.3805]])

In [94]:
# Avoid doing operations with for loops at all cost, they are computationally expensive

%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 602 µs, sys: 0 ns, total: 602 µs
Wall time: 554 µs


tensor(14)

In [95]:
%%time

torch.matmul(tensor1, tensor2)

CPU times: user 124 µs, sys: 0 ns, total: 124 µs
Wall time: 129 µs


tensor([[0.6349, 0.5953],
        [0.5459, 0.3805]])

**Common Error in deep learning (shape Errors)**

In [96]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]], dtype=torch.float32)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B)

In [97]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [98]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [99]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T}\n")
print(f"Multiplying: {tensor_A.shape}*{tensor_B.T.shape} <- Inner Dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

Multiplying: torch.Size([3, 2])*torch.Size([2, 3]) <- Inner Dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [100]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [101]:

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix mutliplcation
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


**Finding the min, max, mean, sum, etc (aggregation)**

In [102]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [103]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") dtype should be float
print(f"Mean: {x.type(torch.float32).mean()}") # Wont work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


**Positional min/max**

In [104]:
tensor = torch.arange(10,100,10)
print(f"Tensor: {tensor}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])


In [105]:
# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Index where max value occurs: 8
Index where min value occurs: 0


**Change Tensor datatype**

In [106]:
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [107]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [108]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

**Reshaping, Stacking, Squeezing and Unsqueezing**

In [109]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [110]:
# Add extra dimension with reshape

x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [111]:
# Change view (Keeps same data as original but changes view)
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [112]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [119]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [120]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [121]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [122]:
# create a tensor with specific shape
x_original = torch.rand(size=(224,224,3))

# permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1) #shift axis: 0->1,1->2,2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Indexing (Selecting data from tensors)**

In [125]:
x = torch.arange(1,10).reshape(1,3,3)

In [126]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [127]:
# Get all values of the 0th dimension and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [131]:
# Get all values of the 0th & 1st dimensions but only index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [132]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimensions

x[:,1,1]

tensor([5])

In [133]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimensin

x[0,0,:]

tensor([1, 2, 3])

**Pytorch tensors and numpy**

In [134]:
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [135]:
# change the array and keep the tensor

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [136]:
# Tensor to numyp array
tensor = torch.ones(7) # dtype=float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility**

In [137]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal to Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal to Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [139]:
import random

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Getting pytorch to run on GPU**

In [141]:
torch.cuda.is_available()

False

In [142]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [143]:
torch.cuda.device_count()

0

**Putting tensors on GPU**

In [146]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

#move tensor to GPU

tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

tensor([1, 2, 3]) cpu


(tensor([1, 2, 3]), device(type='cpu'))

In [147]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])